# -*- coding: utf-8 -*-
"""kahve_makinesi.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gaObGtbCUew_RV_HUghMUeFuibFa0y-q
"""

import time

water = 150
milk = 1000
coffee = 1000

def cappucino():
  global water
  global milk 
  global coffee
  print("your cappucino getting ready")
  time.sleep(2)
  print("getting add water")
  time.sleep(2)
  print("getting add milk")
  time.sleep(2)
  print("getting add coffee")
  time.sleep(2)
  print("your cappucino ready to drink")
  water -= 100
  milk -= 75
  coffee -= 50
  time.sleep(3)
  print("machine ready to your choose")

def latte():
  global water
  global milk 
  global coffee
  print("your latte getting ready")
  time.sleep(2)
  print("getting add water")
  time.sleep(2)
  print("getting add milk")
  time.sleep(2)
  print("getting add coffee")
  time.sleep(2)
  print("your latte ready to drink")
  water -= 100
  milk -= 70
  coffee -= 60
  time.sleep(3)
  print("machine ready to your choose")

def espresso():
  global water
  global milk 
  global coffee
  print("your espresso getting ready")
  time.sleep(2)
  print("getting add water")
  time.sleep(2)
  print("getting add milk")
  time.sleep(2)
  print("getting add coffee")
  time.sleep(2)
  print("your espresso ready to drink")
  water -= 90
  milk -= 65
  coffee -= 55
  time.sleep(3)
  print("machine ready to your choose")

def sum_money_cappicino():
  a = 0
  while True:
    quarter = int(input("how many do you will give me 0.25$ : "))
    dimes = int(input("how many do you will give me 0.10 $ : "))
    nickel = int(input("how many do you will give me 0.05 $ : "))
    pennies = int(input("how many do you will give me 0.01 $ : "))
    a = (a) + (quarter * 0.25) + (dimes * 0.1) + (nickel * 0.05) + (pennies * 0.01)
    if a >= 2.5:
      return a
      break
    else:
      b = input(f"not enough money {2.5 - a} do you want add money [Y/N] : ").upper()
      if b == "N":
        print("please take your money")
        return a
        break

def sum_money_espresso():
  a = 0
  while True:
    quarter = int(input("how many do you will give me 0.25$ : "))
    dimes = int(input("how many do you will give me 0.10 $ : "))
    nickel = int(input("how many do you will give me 0.05 $ : "))
    pennies = int(input("how many do you will give me 0.01 $ : "))
    a = (a) + (quarter * 0.25) + (dimes * 0.1) + (nickel * 0.05) + (pennies * 0.01)
    if a >= 2:
      return a
      break
    else:
      b = input(f"not enough money {2.00 - a} do you want add money [Y/N] : ").upper()
      if b == "N":
        print("please take your money")
        return a
        break

def sum_money_latte():
  a = 0
  while True:
    quarter = int(input("how many do you will give me 0.25$ : "))
    dimes = int(input("how many do you will give me 0.10 $ : "))
    nickel = int(input("how many do you will give me 0.05 $ : "))
    pennies = int(input("how many do you will give me 0.01 $ : "))
    a = (a) + (quarter * 0.25) + (dimes * 0.1) + (nickel * 0.05) + (pennies * 0.01)
    if a >= 2.75:
      return a
      break
    else:
      b = input(f"not enough money {2.75 - a} do you want add money [Y/N] : ").upper()
      if b == "N":
        print("please take your money")
        return a
        break

def cappucino_enough():
  if milk < 75:
    print("Milk is not enough")
    return False
  elif water < 100:
    print("water is not enough")
    return False
  elif coffee < 50:
    print("coffee is not enough")
    return False
  else:
    return True

def espresso_enough():
  if milk < 65:
    print("Milk is not enough")
    return False
  elif water < 90:
    print("water is not enough")
    return False
  elif coffee < 55:
    print("coffee is not enough")
    return False
  else:
    return True

def latte_enough():
  if milk < 70:
    print("Milk is not enough")
    return False
  elif water < 100:
    print("water is not enough")
    return False
  elif coffee < 60:
    print("coffee is not enough")
    return False
  else:
    return True

while True:
 print(f"Have materials\nwater = {water}ml\nmilk = {milk}ml\ncoffee = {coffee}gr")
 drink_choose = int(input("Please enter the number of your choose ? \n1 - espresso\n2 - latte\n3 - cappucino\n"))
 report = input(f"do you want to report for {drink_choose} [Y/N] : ").upper()
 if drink_choose == 3:
  if cappucino_enough():
   if report == "Y":
    print("water = 100 ml\nmilk = 75 ml\ncoffee = 50 gr\nmoney = 2,5$")
   if sum_money_cappicino() >= 2.5:
    cappucino()
 elif drink_choose == 2:
  if latte_enough():
   if report == "Y":
    print("water = 100 ml\nmilk = 70 ml\ncoffee = 60 gr\nmoney = 2,75$")
   if sum_money_latte() >= 2.75:
    latte()
 elif drink_choose == 1:
  if espresso_enough():
   if report == "Y":
    print("water = 90 ml\nmilk = 65 ml\ncoffee = 55 gr\nmoney = 2.00$")
   if sum_money_espresso() >= 2:
    espresso()
 again = input("do you want again choose [Y/N] : ").upper()
 if again == "N":
   print("Thank you for choosing us...")
   break